### ISSUE TITLE
Error in logs: Please provide Conjur Authn Token file or else api Key in environment Variable

### ISSUE THREAD

**Issue by bnasslahsen** [cyberark/conjur-spring-boot-sdk#61]
## Summary

After following all the [configuration steps](https://docs.cyberark.com/Product-Doc/OnlineHelp/AAM-DAP/12.6/en/Content/Integrations/Spring-Boot-Plugin.htm) error are logged, but is does not seem correct.

## Steps to Reproduce

Follow the steps to [Set up the Spring Boot Plugin with Conjur](https://docs.cyberark.com/Product-Doc/OnlineHelp/AAM-DAP/12.6/en/Content/Integrations/Spring-Boot-Plugin.htm#SetuptheSpringBootPluginwithConjur) and see the logs of the application during startup

## Expected Results

*If the variable CONJUR_AUTHN_API_KEY is present. The error should not be logged.*

## Actual Results

2022-07-17 12:51:42.395 **ERROR** 95003 --- [           main] c.c.c.s.core.env.ConjurPropertySource    : Please provide Conjur Authn Token file or else api Key in environment Variable
<img width="1426" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/13404829/179395451-df704730-05dd-4902-b55e-0f74ff618008.png">

## Reproducible

   * [x] Always 
   
## Version/Tag number

* **conjur-sdk-springboot** version `1.0.1`

## Environment setup

* Running on macOS 12.4 / IntelliJ 2022.1.2
* Java version: 11.0.15
* spring-boot 2.7.1
* conjur enterprise 12.6

## Additional Information

*  Some documentation issues and [dead links in the main plugin page](https://docs.cyberark.com/Product-Doc/OnlineHelp/AAM-DAP/12.6/en/Content/Integrations/Spring-Boot-Plugin.htm), that need to be fixed, but maybe GITHUB is not the right place. Feel free to share the right channel to discuss about it.

**Comment by asaraogi** [comment]
Resolved this issue and created PR for the same which is mentioned below.
Fixed patch of Spring boot app starts at 8181 port and error log for api key and authtoken #68
