### ISSUE TITLE
SpringBoot applications start at port 8181 if not port is defined

### ISSUE THREAD

**Issue by bnasslahsen** [cyberark/conjur-spring-boot-sdk#64]
## Summary

*If the application, does not declare `server.port` the default spring-boot port 8080 is changed to 8181 from the` conjur-spring-boot-sdk`*

## Steps to Reproduce

Follow the steps to [Set up the Spring Boot Plugin with Conjur](https://docs.cyberark.com/Product-Doc/OnlineHelp/AAM-DAP/12.6/en/Content/Integrations/Spring-Boot-Plugin.htm#SetuptheSpringBootPluginwithConjur) and see the logs of the application during startup
## Expected Results

*Application server port should not be changed after adding  `conjur-spring-boot-sdk` dependency*

## Actual Results

*Application starts at port 8181*
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/13404829/179424673-d740c8d3-909a-4d3f-b5c3-300d17ac8536.png">

## Reproducible

   * [x] Always

   
## Version/Tag number

* **conjur-sdk-springboot** version `1.0.1`

## Environment setup

* Running on macOS 12.4 / IntelliJ 2022.1.2
* Java version: 11.0.15
* spring-boot 2.7.1
* conjur enterprise 12.6

## Additional Information

To fix this issue, remove `server.port=8181` from application.properties

**Comment by asaraogi** [comment]
Resolved this issue and created PR for the same which is mentioned below.
Fixed patch of Spring boot app starts at 8181 port and error log for api key and authtoken https://github.com/cyberark/conjur-spring-boot-sdk/pull/68
